calibration:
  arm_down_hat_x: 0.1583
  arm_down_hat_y: 0.6748
  arm_down_hat_z: -0.7208
  arm_forward_hat_x: 0.809
  arm_forward_hat_y: 0.5784
  arm_forward_hat_z: 0.1043
  calibrated_at: '2026-09-14T23:33:58.927763+00:00'
  forearm_length_m: 0.2852
  shoulder_offset_x_m: 0.0008
  shoulder_offset_y_m: 0.0008
  shoulder_offset_z_m: -0.0813
  total_arm_length_m: 0.5314
  upper_arm_length_m: 0.2462
