calibration:
  arm_down_hat_x: 0.0329
  arm_down_hat_y: 0.5487
  arm_down_hat_z: -0.8354
  arm_forward_hat_x: 0.7854
  arm_forward_hat_y: 0.5968
  arm_forward_hat_z: 0.164
  calibrated_at: '2026-10-01T13:07:36.639373+00:00'
  forearm_length_m: 0.2314
  shoulder_offset_x_m: 0.0181
  shoulder_offset_y_m: 0.0158
  shoulder_offset_z_m: -0.0889
  total_arm_length_m: 0.5121
  upper_arm_length_m: 0.2807
  wrist_roll_ref_quat:
  - -0.690592
  - 0.194694
  - 0.490339
  - 0.494717
  yaw_offset: -2.3098
