calibration:
  arm_down_hat_x: 0.0104
  arm_down_hat_y: 0.6081
  arm_down_hat_z: -0.7938
  arm_forward_hat_x: 0.6344
  arm_forward_hat_y: 0.7676
  arm_forward_hat_z: 0.0911
  calibrated_at: '2026-09-17T16:11:42.670968+00:00'
  forearm_length_m: 0.2412
  shoulder_offset_x_m: 0.013
  shoulder_offset_y_m: 0.0229
  shoulder_offset_z_m: -0.0823
  total_arm_length_m: 0.503
  upper_arm_length_m: 0.2619
  yaw_offset: -1.6909
